import { execSync, spawn } from "child_process";
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import http from "http";
import fs from "fs";
import path from "path";

describe("Web Frontend Smoke Test", () => {
  let serverProcess: any;

  beforeAll(() => {
    console.log("Building web frontend and backend...");
    // Memory says we might need to downgrade vite or ensure preact is resolved correctly. Let's install preact in web.
    // Memory explicitly states: "To ensure path aliases in 'web/vite.config.ts' resolve correctly during global Vitest runs, 'preact' must be included in the root 'package.json' devDependencies."
    // Also memory states: "If the web frontend fails to build with a 'TypeError: Cannot use in operator to search for meta' error, it is likely due to an incompatibility with Vite 6. Downgrading to vite@5 and @preact/preset-vite@2.8.2 resolves this issue." (Though we got an ENOENT for jsx-dev-runtime instead here).

    // Ensure all packages are installed correctly with npm since we are in an npm-managed project
    // This is a test environment setup so we'll ensure build completes safely.
    execSync("npm run build", { stdio: "inherit" });
  }, 120000); // 2 minutes timeout for building

  afterAll(() => {
    if (serverProcess) {
      serverProcess.kill();
    }
  });

  it("should have generated CSS files in public/assets", () => {
    const assetsDir = path.resolve(__dirname, "../../public/assets");
    expect(fs.existsSync(assetsDir)).toBe(true);

    const files = fs.readdirSync(assetsDir);
    const cssFiles = files.filter((f) => f.endsWith(".css"));

    // We expect at least one compiled CSS file generated by Vite/Tailwind
    expect(cssFiles.length).toBeGreaterThan(0);

    // Read the contents of the generated CSS files
    let combinedCss = "";
    for (const file of cssFiles) {
      combinedCss += fs.readFileSync(path.join(assetsDir, file), "utf-8");
    }

    // Verify CSS is generated for both light and dark themes
    expect(combinedCss).toContain(".dark");
    // Some basic tailwind utility check that might be present
    expect(combinedCss).toContain("bg-bg-light");
  });

  it("should serve the web dashboard at /", async () => {
    // Start the server as a child process
    serverProcess = spawn("node", ["dist/index.js"], {
      cwd: path.resolve(__dirname, "../../"),
      env: {
        ...process.env,
        PORT: "8081", // Use a different port to avoid conflicts with other tests
      },
    });

    // Wait for the server to be ready
    let isReady = false;
    for (let i = 0; i < 30; i++) {
      try {
        const statusCode = await new Promise((resolve, reject) => {
          http
            .get("http://localhost:8081/health", (res) => {
              resolve(res.statusCode);
            })
            .on("error", reject);
        });

        if (statusCode === 200) {
          isReady = true;
          break;
        }
      } catch (e) {
        // Ignore connection refused errors while server is starting
      }
      await new Promise((resolve) => setTimeout(resolve, 500));
    }

    expect(isReady).toBe(true);

    // Fetch the root HTML
    const html: string = await new Promise((resolve, reject) => {
      http
        .get("http://localhost:8081/", (res) => {
          let data = "";
          res.on("data", (chunk) => {
            data += chunk;
          });
          res.on("end", () => {
            resolve(data);
          });
        })
        .on("error", reject);
    });

    // Verify it serves the index.html from Vite build
    expect(html).toContain('<div id="app"></div>');
    expect(html).toContain("Codex Proxy Developer Dashboard");
  }, 15000); // 15s timeout for starting and testing
});
