/**
 * Copy root-level runtime resources into packages/electron/ before
 * electron-builder runs, so all paths resolve relative to projectDir.
 *
 * Usage:
 *   node electron/prepare-pack.mjs          # copy
 *   node electron/prepare-pack.mjs --clean  # remove copies
 */

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";

const ROOT = resolve(import.meta.dirname, "..", "..", "..");
const PKG = resolve(import.meta.dirname, "..");

const DIRS = ["config", "public", "bin"];
const isClean = process.argv.includes("--clean");

for (const dir of DIRS) {
  const src = resolve(ROOT, dir);
  const dest = resolve(PKG, dir);

  if (isClean) {
    if (existsSync(dest)) {
      rmSync(dest, { recursive: true });
      console.log(`[prepare-pack] removed ${dir}/`);
    }
  } else {
    if (!existsSync(src)) {
      console.warn(`[prepare-pack] skipping ${dir}/ (not found at ${src})`);
      continue;
    }
    // Clean destination first to avoid stale files from previous builds
    if (existsSync(dest)) {
      rmSync(dest, { recursive: true });
    }
    cpSync(src, dest, { recursive: true });
    console.log(`[prepare-pack] copied ${dir}/ → packages/electron/${dir}/`);
  }
}

// Native addon — copy only runtime files (index.js, index.d.ts, *.node, package.json),
// skip Rust source, build artifacts (target/), and node_modules.
const nativeSrc = resolve(ROOT, "native");
const nativeDest = resolve(PKG, "native");

if (isClean) {
  if (existsSync(nativeDest)) {
    rmSync(nativeDest, { recursive: true });
    console.log("[prepare-pack] removed native/");
  }
} else if (!existsSync(nativeSrc)) {
  console.warn(`[prepare-pack] skipping native/ (not found at ${nativeSrc})`);
} else {
  cpSync(nativeSrc, nativeDest, {
    recursive: true,
    force: true,
    filter: (src) => {
      const rel = src.slice(nativeSrc.length);
      // Skip Rust source, build artifacts, and node_modules
      if (/\/(target|node_modules|src)(\/|$)/.test(rel)) return false;
      if (/\/(Cargo\.(toml|lock)|build\.rs|\.cargo)/.test(rel)) return false;
      return true;
    },
  });
  console.log("[prepare-pack] copied native/ (runtime only) → packages/electron/native/");
}

// Electron 的后端 bundle 是 ESM，`ws` 这类 CJS 包不能被 esbuild 安全内联。
// 这里把被 external 的运行时依赖从 workspace 根 node_modules 复制进 app 包。
const RUNTIME_PACKAGES = ["ws", "https-proxy-agent", "socks-proxy-agent"];
const RUNTIME_COPY_MARKER = ".codex-proxy-runtime-copy";

function packageDest(pkgName) {
  return resolve(PKG, "node_modules", ...pkgName.split("/"));
}

function findPackageDir(pkgName) {
  const pkgDir = resolve(ROOT, "node_modules", ...pkgName.split("/"));
  if (existsSync(resolve(pkgDir, "package.json"))) {
    return pkgDir;
  }
  throw new Error(`无法定位运行时依赖 ${pkgName} 的 package.json`);
}

function collectRuntimePackages(pkgName, seen = new Set()) {
  if (seen.has(pkgName)) return seen;
  seen.add(pkgName);

  const pkgDir = findPackageDir(pkgName);
  const manifest = JSON.parse(readFileSync(resolve(pkgDir, "package.json"), "utf-8"));
  for (const depName of Object.keys(manifest.dependencies ?? {})) {
    collectRuntimePackages(depName, seen);
  }
  return seen;
}

function copyRuntimePackage(pkgName) {
  const pkgDir = findPackageDir(pkgName);
  const dest = packageDest(pkgName);
  const marker = resolve(dest, RUNTIME_COPY_MARKER);
  if (existsSync(dest)) {
    if (!existsSync(marker)) {
      console.log(`[prepare-pack] 使用已有运行时依赖 ${pkgName}`);
      return;
    }
    rmSync(dest, { recursive: true });
  }
  mkdirSync(dirname(dest), { recursive: true });
  cpSync(pkgDir, dest, {
    recursive: true,
    filter: (src) => {
      const rel = src.slice(pkgDir.length);
      return !/\/node_modules(\/|$)/.test(rel);
    },
  });
  writeFileSync(resolve(dest, RUNTIME_COPY_MARKER), "generated by prepare-pack\n", "utf-8");
  console.log(`[prepare-pack] 已复制运行时依赖 ${pkgName}`);
}

function removeRuntimePackage(pkgName) {
  const dest = packageDest(pkgName);
  if (existsSync(resolve(dest, RUNTIME_COPY_MARKER))) {
    rmSync(dest, { recursive: true });
    console.log(`[prepare-pack] 已移除运行时依赖 ${pkgName}`);
  }
  const scopeDir = pkgName.startsWith("@")
    ? resolve(PKG, "node_modules", pkgName.split("/")[0])
    : null;
  if (scopeDir && existsSync(scopeDir) && readdirSync(scopeDir).length === 0) {
    rmSync(scopeDir, { recursive: true });
  }
}

const runtimePackages = RUNTIME_PACKAGES.flatMap((pkgName) => [...collectRuntimePackages(pkgName)])
  .filter((pkgName, index, all) => all.indexOf(pkgName) === index);

if (isClean) {
  for (const pkgName of runtimePackages.reverse()) {
    removeRuntimePackage(pkgName);
  }
} else {
  for (const pkgName of runtimePackages) {
    copyRuntimePackage(pkgName);
  }
}
