name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Build web
      run: pnpm run build:web

    - name: Build backend
      run: pnpm run build

    - name: Build electron
      run: cd packages/electron && pnpm run build

    - name: Run tests
      run: xvfb-run pnpm test
